summary: Manage compile and link flags for libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-linux-x86_64/releases/download/2022.12.11/pkg-config-0.29.2-linux-x86_64.tar.xz
bin-sha: 5ec10e5fa2e945410c0ced34c2d753d0c9350a25783a6b18ea9c3972e1de1109
